# Project information
site_name: BreatheDocs
site_url: https://shawnlxf.github.io/mkdocs/
site_author: Shawn
site_description: >-
  前端学习笔记，包含饥人谷方方课的笔记，MDN 的学习总结，读书笔记 和 项目记录 等。

# Repository
repo_name: shawnlxf/mkdocs
repo_url: https://github.com/shawnlxf/mkdocs

# Copyright
copyright: Copyright &copy; 2020 Shawn

# Configuration
theme:
  name: material
  favicon: img/呼吸内科.svg
  logo: img/呼吸内科.svg
  language: zh
  features:
    - tabs

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/shawnlxf
    - icon: fontawesome/brands/codepen
      link: https://codepen.io/shawnlxf/pens/loved
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/shawn02745544

# Extensions
markdown_extensions:
  - admonition
  # 区块代码高亮
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  # nest code blocks within other blocks
  - pymdownx.superfences
  # collapsible Admonition blocks
  - pymdownx.details
  # 使用 shebang 可以在一行文本里实现代码高亮
  - pymdownx.inlinehilite
  # grouping Markdown blocks with tabs
  - pymdownx.tabbed

# Page tree
nav:
  - Home: 
      - 前端学习: index.md
      - 日常:
          - ninja 说明书: help.md
          - 万维钢-精英日课1: Books/精英日课1.md
          - 圣经: Books/圣经.md
          - 精要主义: Books/精要主义.md
      - English 日常:
          - 1: Others/English/1.md
          - 2: Others/English/2.md
          - 3: Others/English/3.md
      - MDN-术语表: mdn-glossary.md
      - Learn-大纲: MDN-Learn/0.md
      - Learn-Web 入门: MDN-Learn/1.md
      - Learn-常见问题: MDN-Learn/10.md
      - Web-大纲: MDN-Web/0.md
      - Web-HTTP: MDN-Web/http-1.md
      - 项目:
          - 1: Projects/1.md
      - Books:
          - 你不知道的 JavaScript: Books/你不知道的JavaScript.md
          - 锋利的 jQuery: Books/锋利的jQuery.md
          - 网道-JavaScript:
              - 1-入门篇: Books/网道-JavaScript/1.md
              - 2-数据类型: Books/网道-JavaScript/2.md
          - 网道-HTML: Books/网道-HTML.md
  - HTML:
      - 方方-语法/标签: FF/3.md
      - 方方-重点标签: FF/4.md
      - Learn-简介: MDN-Learn/html-1.md
      - Web-元素: MDN-Web/html-1.md
      - Web-全局属性: MDN-Web/html-2.md
      - Web-章节标签/文本标签: MDN-Web/html-3.md
      - Web-a/img/table/form: MDN-Web/html-4.md
      - Web-inline/block: MDN-Web/html-5.md
  - CSS:
      - 方方-基础概念: FF/5.md
      - 方方-布局/float/flex/grid: FF/6.md
      - 方方-定位: FF/7.md
      - 方方-动画: FF/8.md
      - Learn-第一步: MDN-Learn/css-1.md
      - Learn-构建块: MDN-Learn/css-2.md
      - Learn-布局1: MDN-Learn/css-layout-1.md
      - Learn-布局2: MDN-Learn/css-layout-2.md
      - Web-ref-property: MDN-Web/css-ref-1.md
      - Web-ref-概念: MDN-Web/css-ref-2.md
      - Web-关键概念: MDN-Web/css-2.md
  - JavaScript:
      - Learn-第一步: MDN-Learn/js-1.md
      - Learn-构建块: MDN-Learn/js-2.md
      - Learn-对象: MDN-Learn/js-3.md
      - Web-ref: MDN-Web/js-ref.md
      - Web-ref-built-ins: MDN-Web/js-ref-built-ins.md
      - Web-JS: MDN-Web/js.md
      - W3c-DOM-Document: Network/w3c-dom-document.md
      - W3c-DOM-Element: Network/w3c-dom-element.md
      - W3c-DOM-Window: Network/w3c-dom-window.md
      - W3c-JS-RegExp: Network/w3c-js-regexp.md
      - W3c-JS-String: Network/w3c-js-string.md
      - W3c-JS-Array: Network/w3c-js-array.md
      - W3c-JS-Number: Network/w3c-js-number.md
      - W3c-JS-JSON: Network/w3c-js-json.md
      - W3c-JS-AJAX: Network/w3c-js-ajax.md
      - W3c-JS-jQuery: Network/w3c-js-jquery.md
      - W3c-JS-Math: Network/w3c-js-math.md
      - 方方-概述/内存图: FF/10.md
      - 方方-语法/数据类型/运算符: FF/11.md
      - 方方-对象/对象分类: FF/12.md
      - 方方-数组: FF/13.md
      - 方方-函数: FF/14.md
      - 方方-运算符/总结: FF/15.md
      - 方方-DOM 编程: FF/17.md
      - 方方-封装 DOM: FF/18.md
      - 方方-DOM 事件与事件委托: FF/19.md
      - 方方-前后端分离: FF/20.md
  #- Vue.js:
  #- 小程序:
  #- React.js:
  - 算法:
      - 方方-伪代码与流程图: FF/16.md
  - 其他:
      - 方方-杂项: FF/0.md
      - 方方-快捷键/node.js: FF/1.md
      - 方方-git/markdown: FF/2.md
      - 方方-HTTP入门/请求与响应/node.js: FF/9.md
      - 工具:
          - 常用软件: Others/Tools/software.md
          - Git: Others/Tools/git.md
          - Github: Others/Tools/github.md
          - MkDocs: Others/Tools/mkdocs.md
          - Cmder: Others/Tools/cmder.md
          - npm/yarn: Others/Tools/npm-yarn.md
      - 语言:
          - markdown: Others/Language/markdown.md
          - bash: Others/Language/bash.md
          - JSON: Others/Language/json.md
  - Blog:
      - 0-Github Pages: Blog/0.md
      - 4-CSS 知识总结: Blog/4.md
      - 5-浅析 URL: Blog/5.md
      - 6-JavaScript 的诞生: Blog/6.md
      - 7-JS 的基本语法: Blog/7.md
      - 8-JS 对象基本用法: Blog/8.md
      - 9-JS 函数的执行时机: Blog/9.md
      - 10-jQuery 的功能: Blog/10.md
      - 11-Module Pattern: Blog/11.md
