# Project information
site_name: Everyday Docs
site_url: https://shawnlxf.github.io/mkdocs/
site_author: Shawn
site_description: >-
  前端学习笔记，包含饥人谷方方课的笔记，MDN 的学习总结，读书笔记 和 项目记录 等。

# Repository
repo_name: shawnlxf/mkdocs
repo_url: https://github.com/shawnlxf/mkdocs

# Copyright
copyright: Copyright &copy; 2020 Shawn

# Configuration
theme:
  name: material
  language: zh
  features:
    - tabs

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/shawnlxf
    - icon: fontawesome/brands/codepen
      link: https://codepen.io/shawnlxf/pens/loved
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/shawn20111416

# Extensions
markdown_extensions:
  - admonition
  # 区块代码高亮
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  # nest code blocks within other blocks
  - pymdownx.superfences
  # collapsible Admonition blocks
  - pymdownx.details
  # 使用 shebang 可以在一行文本里实现代码高亮
  - pymdownx.inlinehilite
  # grouping Markdown blocks with tabs
  - pymdownx.tabbed

# Page tree
nav:
  - 健康:
      - index.md
      - 1-高血压: health/1.md
      - 2-预防冠心病/血栓: health/2.md
      - 宜忌: health/宜忌.md
      - 关灯就睡觉: health/关灯就睡觉.md
      - 失眠调养/失眠症: health/失眠调养-失眠症.md
      - 失眠星人自救指南: health/失眠星人自救指南.md
      - 冠心病: health/冠心病.md
      - 做自己的心脑健康医生: health/做自己的心脑健康医生.md
      - 应季蔬果: health/应季蔬果.md
  - 工作:
      - 事业单位:
          - 面试: work/public-institution/interview.md
      - 三菱-PLC: work/三菱-PLC.md
      - 八方汇: work/八方汇.md
      - 煤气: work/煤气.md
  - 学习:
      - study/index.md
      - 个人管理:
          - 万维钢-精英日课1: study/personal-control/精英日课1.md
          - 精要主义: study/personal-control/精要主义.md
          - 金发姑娘原则: study/personal-control/金发姑娘原则.md
      - 单词:
          - mkdocs-material: study/english-words/mkdocs-material.md
          - 1: study/english-words/1.md
          - 2: study/english-words/2.md
          - 3: study/english-words/3.md
      - 工具:
          - 常用软件: study/tools/software.md
          - git: study/tools/git.md
          - github: study/tools/github.md
          - mkdocs: study/tools/mkdocs.md
          - cmder: study/tools/cmder.md
          - npm/yarn: study/tools/npm-and-yarn.md
          - 方方-shell/git/markdown/其他: study/tools/fangfang.md
      - 语言:
          - markdown: study/computer-languages/markdown.md
          - bash: study/computer-languages/bash.md
  - 生活:
      - 做菜:
          - 蒸菜: life/cooking/蒸菜.md
          - 食谱: life/cooking/食谱.md
          - 买锅: life/cooking/买锅.md
      - 说明书: life/instructions.md
      - vpn: life/vpn.md
      - 显示器/防蓝光眼镜: life/moniter.md
  - 前端（放弃）:
      - front-end/index.md
      - 其他:
          - 方方-杂项: front-end/FF/0.md
          - 方方-快捷键/node.js: front-end/FF/1.md
          - 方方-HTTP入门/请求与响应/node.js: front-end/FF/9.md
          - 方方-vue: front-end/FF/22.md
          - Learn-Web入门: front-end/MDN-Learn/1.md
          - Learn-常见问题: front-end/MDN-Learn/10.md
          - Web-HTTP: front-end/MDN-Web/http-1.md
          - MDN-术语表: front-end/mdn-glossary.md
          - 工具-前端:
              - 常用软件: front-end/Others/Tools/software.md
          - 语言:
              - JSON: front-end/Others/Language/json.md
      - Learn-大纲: front-end/MDN-Learn/0.md
      - Web-大纲: front-end/MDN-Web/0.md
      - HTML:
          - 方方-语法/标签: front-end/FF/3.md
          - 方方-重点标签: front-end/FF/4.md
          - Learn-简介: front-end/MDN-Learn/html-1.md
          - Web-元素: front-end/MDN-Web/html-1.md
          - Web-全局属性: front-end/MDN-Web/html-2.md
          - Web-章节标签/文本标签: front-end/MDN-Web/html-3.md
          - Web-a/img/table/form: front-end/MDN-Web/html-4.md
          - Web-inline/block: front-end/MDN-Web/html-5.md
      - CSS:
          - 方方-基础概念: front-end/FF/5.md
          - 方方-布局/float/flex/grid: front-end/FF/6.md
          - 方方-定位: front-end/FF/7.md
          - 方方-动画: front-end/FF/8.md
          - Learn-第一步: front-end/MDN-Learn/css-1.md
          - Learn-构建块: front-end/MDN-Learn/css-2.md
          - Learn-布局1: front-end/MDN-Learn/css-layout-1.md
          - Learn-布局2: front-end/MDN-Learn/css-layout-2.md
          - Web-ref-property: front-end/MDN-Web/css-ref-1.md
          - Web-ref-概念: front-end/MDN-Web/css-ref-2.md
          - Web-关键概念: front-end/MDN-Web/css-2.md
      - JavaScript:
          - Learn-第一步: front-end/MDN-Learn/js-1.md
          - Learn-构建块: front-end/MDN-Learn/js-2.md
          - Learn-对象: front-end/MDN-Learn/js-3.md
          - Web-ref: front-end/MDN-Web/js-ref.md
          - Web-ref-built-ins: front-end/MDN-Web/js-ref-built-ins.md
          - Web-闭包: front-end/MDN-Web/js-closure.md
          - W3-DOM: front-end/Network/w3-dom.md
          - W3-JavaScript: front-end/Network/w3-javascript.md
          - W3-JS-Tutorial: front-end/Network/w3-js-tutorial.md
          - W3c-JS-Number: front-end/Network/w3c-js-number.md
          - W3c-JS-Math: front-end/Network/w3c-js-math.md
          - W3c-JS-AJAX: front-end/Network/w3c-js-ajax.md
          - W3c-JS-jQuery: front-end/Network/w3c-js-jquery.md
          - 方方-概述/内存图: front-end/FF/10.md
          - 方方-语法/数据类型/运算符: front-end/FF/11.md
          - 方方-对象/对象分类: front-end/FF/12.md
          - 方方-数组: front-end/FF/13.md
          - 方方-函数: front-end/FF/14.md
          - 方方-运算符/总结: front-end/FF/15.md
          - 方方-DOM编程: front-end/FF/17.md
          - 方方-封装DOM: front-end/FF/18.md
          - 方方-DOM事件与事件委托: front-end/FF/19.md
          - 方方-前后端分离: front-end/FF/20.md
          - 方方-webpack: front-end/FF/21.md
      - 算法:
          - 方方-伪代码与流程图: front-end/FF/16.md
      - Blog:
          - 4-CSS知识总结: front-end/Blog/4.md
          - 5-浅析URL: front-end/Blog/5.md
          - 6-JavaScript的诞生: front-end/Blog/6.md
          - 7-JS的基本语法: front-end/Blog/7.md
          - 8-JS对象基本用法: front-end/Blog/8.md
          - 9-JS函数的执行时机: front-end/Blog/9.md
          - 10-jQuery的功能: front-end/Blog/10.md
          - 11-Module Pattern: front-end/Blog/11.md
          - 12-期中考试: front-end/Blog/12.md
          - 13-浅析MVC: front-end/Blog/13.md
      - 项目:
          - 1: front-end/Projects/1.md
      - Books:
          - 锋利的jQuery: front-end/Books/锋利的jQuery.md
          - 网道-JavaScript:
              - 1-入门篇: front-end/Books/网道-JavaScript/1.md
              - 2-数据类型: front-end/Books/网道-JavaScript/2.md


