site_name: ShawnDocs
nav:
  - Home: "README.md"
  - MDN-Learn: "MDN-Learn/0.md"
  - English:
      - "1": "English/1.md"
  - FF:
      - "0-杂项": "FF/0.md"
      - "1-安装": "FF/1.md"
      - "2-git-markdown-Hugo": "FF/2.md"
      - "3-HTML语法-HTML标签": "FF/3.md"
      - "4-HTML重点标签": "FF/4.md"
      - "5-CSS基础概念": "FF/5.md"
      - "6-CSS布局": "FF/6.md"
      - "7-CSS定位": "FF/7.md"
      - "8-CSS动画": "FF/8.md"
      - "9-HTTP入门": "FF/9.md"
      - "10-JS": "FF/10.md"
  - tools:
      - "Git": "tools/git.md"
      - "Github": "tools/github.md"
      - "Hugo": "tools/hugo.md"
      - "Mkdocs": "tools/mkdocs.md"
  - language:
      - "HTML": "language/html.md"
      - "Markdown": "language/markdown.md"
      - "Bash": "language/bash.md"

theme: material
markdown_extensions:
  - toc:
      permalink: "#"
