# Project information
site_name: ShawnDocs

# Repository
repo_name: shawnlxf/mkdocs
repo_url: https://github.com/shawnlxf/mkdocs

# Copyright
copyright: Copyright &copy; 2020 Shawn

# Configuration
theme:
  name: material
  favicon: img/ninja.svg
  logo: img/ninja.svg
  language: zh
  features:
    - tabs

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/shawnlxf
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/shawn02745544
    - icon: fontawesome/brands/zhihu
      link: https://www.zhihu.com/people/lin-xiao-feng-28-63
    - icon: fontawesome/brands/weixin
      link: img/wechat.png

# Extensions
markdown_extensions:
  - admonition
  # 区块代码高亮
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  # nest code blocks within other blocks
  - pymdownx.superfences
  # collapsible Admonition blocks
  - pymdownx.details
  # 使用 shebang 可以在一行文本里实现代码高亮
  - pymdownx.inlinehilite
  # grouping Markdown blocks with tabs
  - pymdownx.tabbed

# Page tree
nav:
  - Home: index.md
  - 方方:
      - 0-杂项: FF/0.md
      - 1-安装: FF/1.md
      - 2-git / markdown / Hugo: FF/2.md
      - 3-HTML语法 / 标签: FF/3.md
      - 4-HTML重点标签: FF/4.md
      - 5-CSS基础概念: FF/5.md
      - 6-CSS布局: FF/6.md
      - 7-CSS定位: FF/7.md
      - 8-CSS动画: FF/8.md
      - 9-HTTP入门 / 请求与响应 / node.js: FF/9.md
      - 10-JS概述 / 内存图: FF/10.md
      - 11-JS语法 / 数据类型 / 运算符: FF/11.md
      - 12-JS对象 / 对象分类: FF/12.md
      - 13-JS数组: FF/13.md
      - 14-JS函数: FF/14.md
  - Learn:
      - MDN-Learn:
          - 大纲: MDN-Learn/0.md
          - Web 入门: MDN-Learn/1.md
          - CSS: MDN-Learn/css.md
          - 常见问题: MDN-Learn/10.md
      - MDN-Web:
          - Web: MDN-Web/0.md
          - HTML: MDN-Web/1.md
          - CSS: MDN-Web/2.md
      - Books:
          - 你不知道的JavaScript: Learn/Books/你不知道的JavaScript.md
          - 阮一峰的JS教程: Learn/Books/阮一峰的JS教程.md
      - Projects:
          - 1: Learn/Projects/1.md
  - Skills:
      - Language:
          - HTML: Skills/Language/html.md
          - CSS: Skills/Language/css.md
          - JavaScript: Skills/Language/javascript.md
          - Markdown: Skills/Language/markdown.md
          - Bash: Skills/Language/bash.md
      - Tools:
          - Software: Skills/Tools/software.md
          - Git: Skills/Tools/git.md
          - Github: Skills/Tools/github.md
          - Hugo: Skills/Tools/hugo.md
          - MkDocs: Skills/Tools/mkdocs.md
          - Cmder: Skills/Tools/cmder.md
      - English:
          - 1: Skills/English/1.md
          - 2: Skills/English/2.md
  - Blog:
      - 1-Github Pages: Blog/1.md
      - 2-HTML入门笔记1: Blog/2.md
      - 3-HTML常用标签: Blog/3.md
      - 4-CSS知识总结: Blog/4.md
      - 5-浅析URL: Blog/5.md
      - 6-JavaScript的诞生: Blog/6.md
      - 7-JS的基本语法: Blog/7.md
      - 8-JS对象基本用法: Blog/8.md
      - 9-JS函数的执行时机: Blog/9.md
