site_name: ShawnDocs
nav:
  - Web: "web.md"
  - Web入门:
      - "1": "Web入门/1.md"
      - "2": "Web入门/2.md"
  - FF:
      - "1-安装": "FF/1.md"
      - "2-git-markdown-Hugo": "FF/2.md"
      - "3-HTML语法-HTML标签": "FF/3.md"
      - "4-HTML重点标签": "FF/4.md"
      - "5-CSS基础概念": "FF/5.md"
      - "6-CSS布局": "FF/6.md"
      - "7-CSS定位": "FF/7.md"
      - "8-CSS动画": "FF/8.md"
      - "9-HTTP入门": "FF/9.md"
      - "10-JS": "FF/10.md"
  - HTML:
      - "Help": "HTML/help.md"
      - "Elements": "HTML/elements.md"
      - "1": "HTML/1.md"
  - Home: "README.md"
  - Hugo: "hugo.md"
  - Git: "git.md"
  - Software: "software.md"
  - Markdown:
      - "Help": "Markdown/help.md"
  - shell:
      - "Help": "shell/help.md"
      - "1": "shell/1.md"

theme: material
markdown_extensions:
  - toc:
      permalink: "#"
